apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-with-baseline
  labels:
    app: analysis-with-baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-with-baseline
  template:
    metadata:
      labels:
        app: analysis-with-baseline
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.1.0-71-g771df05
        args:
          - server
        ports:
        - containerPort: 9085
