# This deployment has an Approval stage to wait until got
# an approval from one of the specified approvers.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: WAIT_APPROVAL
        with:
          approvers:
            - nghialv
      - name: K8S_PRIMARY_UPDATE
