apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-steps-canary
  labels:
    app: multi-steps-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-steps-canary
  template:
    metadata:
      labels:
        app: multi-steps-canary
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.1.0-71-g771df05
        args:
          - server
        ports:
        - containerPort: 9085
