apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-by-log
  labels:
    app: analysis-by-log
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-by-log
  template:
    metadata:
      labels:
        app: analysis-by-log
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.1.0-71-g771df05
        args:
          - server
        ports:
        - containerPort: 9085
