apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      # Deploy the workloads of CANARY variant. In this case, the number of
      # workload replicas of CANARY variant is 10% of the replicas number of PRIMARY variant.
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      # The percentage of traffic each variant should receive.
      # In this case, CANARY variant will receive 10% of traffic,
      # while PRIMARY will receive 90% of traffic.
      - name: K8S_TRAFFIC_SPLIT
        with:
          canary: 10
      # Update the workload of PRIMARY variant to the new version.
      - name: K8S_PRIMARY_UPDATE
      # The percentage of traffic each variant should receive.
      # In this case, PRIMARY variant will receive all of the traffic.
      - name: K8S_TRAFFIC_SPLIT
        with:
          primary: 100
      # Destroy all workloads of CANARY variant.
      - name: K8S_CANARY_CLEAN
